# Generated by Django 4.0.4 on 2022-04-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='meetingminutes',
            new_name='minutestext',
        ),
        migrations.RemoveField(
            model_name='meetingminutes',
            name='meetingidtype',
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='meetingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Club.meeting'),
        ),
    ]
